

services:
 
# --------------------  
#       API SCRAP 
#  -------------------

  api-scrap:
    build: ./api_scrap/.
    container_name: api-scrap
    ports:
      - "${API_SCRAP_PORT}:${API_SCRAP_PORT}"
    restart: always
    
    env_file: .env
    environment:
      - ENVIRONMENT=prod
    # --- prod
    #command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${API_ELASTIC_PORT}"]
    
    #  ---- dev
    volumes:
      - ./api_scrap/app:/app/app  # Montage des fichiers source pour le hot-reload
    command: ["uvicorn", "app.main:app", "--reload", "--reload-dir", "/app/app", "--host", "0.0.0.0", "--port", "${API_SCRAP_PORT}"]
    networks:
      - jobsearch_network 
    
networks:
  jobsearch_network:
    external: true
    name: jobsearch_network


