services:
  streamlit:
    build: ./streamlit_front
    container_name: streamlit
    ports:
      - "8501:8501"
    env_file: .env
    restart: always
    mem_limit: 400m
    cpus: 1.0
    networks:
      - jobsearch_network

networks:
  jobsearch_network:
    external: true
