

services:
 
# --------------------  
#       API SCRAP 
#  -------------------

  api-scrap:
    build: ./api_scrap/.
    container_name: api-scrap
    ports:
      - "${API_SCRAP_PORT}:${API_SCRAP_PORT}"
    restart: always
    depends_on:
      - celery
      - rabbitmq
      - redis
    env_file: .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    networks:
      - jobsearch_network 
    
networks:
  jobsearch_network:
    external: true
    name: jobsearch_network


