# version: "3.9"

services:
      
  api_scrap:
    build: .
    container_name: api-scrap
    ports:
      - "${API_SCRAP_PORT}:${API_SCRAP_PORT}"
    restart: always
    env_file: .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${API_SCRAP_PORT}"]
    environment:
      - ENVIRONMENT=prod
    networks:
      - jobsearch_network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      - jobsearch_network

networks:
  jobsearch_network:
    external: true
    name: jobsearch_network

