services:

  api-postgres:
    build: .
    container_name: api-postgres
    ports:
      - "${API_POST_PORT}:${API_POST_PORT}"
    restart: always
    depends_on:
      - pgdatabase
    env_file: .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${API_POST_PORT}"]
    environment:
      - ENVIRONMENT=prod

  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    env_file: .env
    environment:
      - ENVIRONMENT=prod
    volumes:
      - job_market_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8081:80"

# ---------- VOLUMES ----------
volumes:
  job_market_data:
  data_pgadmin:

# networks:
#   jobsearch_network:
#     # external: true

