services:
  elastic_api:
    build: .
    container_name: elastic-api
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - elasticsearch
    env_file: ./app/.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - ENVIRONMENT=prod
    networks:
      - jobsearch_network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
    env_file: ./app/.env
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - jobsearch_network

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    restart: always
    env_file: ./app/.env
    networks:
      - jobsearch_network

# ---------- VOLUMES ----------
volumes:
  elasticsearch-data:
  kibana-data:

networks:
  jobsearch_network:
    external: true

